# You need to provide details about yourself that we can use to contact you.
[user]
username = "Itera"
# You have to have one of these.
email = "scarsnetwork@outlook.com"
discord = ""

[records]
# Your site's records, i.e.
CNAME = "iteraruiner.netlify.app"
